import { PrismaClient } from '@prisma/client'
// Client is regenerated by `prisma generate` (run via `postinstall`).
// Use `bun run db:migrate` (dev) or `bun run db:deploy` (prod) to apply migrations.

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
}

export const db =
  globalForPrisma.prisma ??
  new PrismaClient({
    // Query logging is noisy (and slower) in production - dev only.
    log: process.env.NODE_ENV === 'development' ? ['query'] : [],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = db